In [1]:
import pandas as pd

from pathlib import Path

RUN_ID = "run_2610281804"
OUT_DIR = "../out/"
RUN_DIR = Path(OUT_DIR) / RUN_ID
RUN_DIR

PosixPath('../out/run_2610281804')

In [2]:
final_design_metrics_csv = pd.read_csv(Path(RUN_DIR) / "final_ranked_designs" / "final_designs_metrics_30.csv")
final_design_metrics_csv.head()

,id,final_rank,designed_sequence,designed_chain_sequence,num_design,design_to_target_iptm,min_design_to_target_pae,design_ptm,filter_rmsd,designfolding-filter_rmsd,...,rank_design_to_target_iptm,rank_design_ptm,rank_neg_min_design_to_target_pae,rank_plip_hbonds_refolded,rank_plip_saltbridge_refolded,rank_delta_sasa_refolded,max_rank,secondary_rank,quality_score,sequence
0,bg_hs_tfr1_near_apical_4,1,KLKEEALKLLEEAKKLIEEGDIDGALEHLEKALEVARKLDLESRKE...,KLKEEALKLLEEAKKLIEEGDIDGALEHLEKALEVARKLDLESRKE...,63,0.73020,6.35154,0.88220,0.81904,0.45156,...,2.0,2.0,2.0,0.5,1.0,0.5,2.0,1,1.000000,KLKEEALKLLEEAKKLIEEGDIDGALEHLEKALEVARKLDLESRKE...
1,bg_hs_tfr1_near_apical_2,2,LLEKALEALEAGKLDEAIELLLDAARKLQEEGLLTDEVVNNITKAL...,LLEKALEALEAGKLDEAIELLLDAARKLQEEGLLTDEVVNNITKAL...,71,0.74655,4.91822,0.87376,0.84875,0.47044,...,1.0,3.0,1.0,1.0,1.5,1.0,3.0,2,0.888889,LLEKALEALEAGKLDEAIELLLDAARKLQEEGLLTDEVVNNITKAL...
2,bg_hs_tfr1_near_apical_0,3,SLLKVEKDGKVVGYLEDGVLYCRPGVVKVGDKVTLINPKTGKKEEA...,SLLKVEKDGKVVGYLEDGVLYCRPGVVKVGDKVTLINPKTGKKEEA...,59,0.33812,17.16698,0.95281,0.91805,0.52912,...,3.0,1.0,3.0,1.5,0.5,1.5,3.0,2,0.777778,SLLKVEKDGKVVGYLEDGVLYCRPGVVKVGDKVTLINPKTGKKEEA...
3,bg_hs_tfr1_near_apical_5,4,LLTGGGVTVTFEGLPEGEGAGVGVRTAGGAPAGGGGAGAGGTAGGG...,LLTGGGVTVTFEGLPEGEGAGVGVRTAGGAPAGGGGAGAGGTAGGG...,87,0.38512,16.13894,0.63431,4.08939,5.59157,...,5.0,6.0,6.0,2.0,2.5,2.5,6.0,3,0.666667,LLTGGGVTVTFEGLPEGEGAGVGVRTAGGAPAGGGGAGAGGTAGGG...
4,bg_hs_tfr1_near_apical_8,5,LERLAELLGVGLLLLGEGLELLGEGALLGEDAAAGEGLEELLELLD...,LERLAELLGVGLLLLGEGLELLGEGALLGEDAAAGEGLEELLELLD...,90,0.41316,10.44283,0.60733,7.11685,4.54298,...,4.0,7.0,4.0,2.5,2.0,3.0,7.0,4,0.555556,LERLAELLGVGLLLLGEGLELLGEGALLGEDAAAGEGLEELLELLD...

In [3]:
final_design_metrics_csv[["interaction_pae", "design_ptm", "design_iptm"]]

   interaction_pae  design_ptm  design_iptm
0         16.17085     0.88220      0.73020
1         16.11913     0.87376      0.74655
2         24.93900     0.95281      0.33812
3         25.53424     0.63431      0.38512
4         24.69122     0.60733      0.41316
5         23.91495     0.92221      0.37558
6         25.88073     0.44638      0.36883
7         25.81361     0.38934      0.38366
8         25.91673     0.54201      0.36224
9         25.96756     0.95275      0.30890

In [4]:
dict(final_design_metrics_csv.iloc[0])

{'id': 'bg_hs_tfr1_near_apical_4',
 'final_rank': np.int64(1),
 'designed_sequence': 'KLKEEALKLLEEAKKLIEEGDIDGALEHLEKALEVARKLDLESRKEILEKIIELLKELRKKIE',
 'designed_chain_sequence': 'KLKEEALKLLEEAKKLIEEGDIDGALEHLEKALEVARKLDLESRKEILEKIIELLKELRKKIE',
 'num_design': np.int64(63),
 'design_to_target_iptm': np.float64(0.7302),
 'min_design_to_target_pae': np.float64(6.35154),
 'design_ptm': np.float64(0.8822),
 'filter_rmsd': np.float64(0.81904),
 'designfolding-filter_rmsd': np.float64(0.45156),
 'plip_hbonds_refolded': np.int64(4),
 'delta_sasa_refolded': np.float64(1051.61328),
 'design_largest_hydrophobic_patch_refolded': np.float64(835.42358),
 'design_chain_hydrophobicity': np.float64(51.178),
 'design_hydrophobicity': np.float64(51.178),
 'loop': np.float64(0.14286),
 'helix': np.float64(0.85714),
 'sheet': np.float64(0.0),
 'file_name': 'bg_hs_tfr1_near_apical_4.cif',
 'num_prot_tokens': np.int64(1341),
 'num_lig_atoms': np.int64(0),
 'num_resolved_tokens': np.float64(1341.0),
 'num_tokens': np.float64(1341.0),
 'UNK_fraction': np.float64(0.0),
 'GLY_fraction': np.float64(0.03175),
 'ALA_fraction': np.float64(0.07937),
 'CYS_fraction': np.float64(0.0),
 'SER_fraction': np.float64(0.01587),
 'PRO_fraction': np.float64(0.0),
 'THR_fraction': np.float64(0.0),
 'VAL_fraction': np.float64(0.01587),
 'ILE_fraction': np.float64(0.09524),
 'ASN_fraction': np.float64(0.0),
 'ASP_fraction': np.float64(0.04762),
 'LEU_fraction': np.float64(0.22222),
 'MET_fraction': np.float64(0.0),
 'GLN_fraction': np.float64(0.0),
 'GLU_fraction': np.float64(0.2381),
 'LYS_fraction': np.float64(0.19048),
 'HIS_fraction': np.float64(0.01587),
 'PHE_fraction': np.float64(0.0),
 'ARG_fraction': np.float64(0.04762),
 'TYR_fraction': np.float64(0.0),
 'TRP_fraction': np.float64(0.0),
 'liability_score': np.int64(160),
 'liability_num_violations': np.int64(16),
 'liability_high_severity_violations': np.int64(16),
 'liability_medium_severity_violations': np.int64(0),
 'liability_low_severity_violations': np.int64(0),
 'liability_AspCleave_count': np.int64(0),
 'liability_ProtTryp_count': np.int64(0),
 'liability_HydroPatch_count': np.int64(0),
 'liability_UnpairedCys_count': np.float64(nan),
 'liability_NTCycl_count': np.int64(0),
 'liability_NTCycl_position': np.int64(-1),
 'liability_NTCycl_length': np.int64(0),
 'liability_NTCycl_severity': np.int64(0),
 'liability_NTCycl_details': np.float64(nan),
 'liability_NTCycl_positions': np.float64(nan),
 'liability_NTCycl_num_positions': np.int64(0),
 'liability_NTCycl_global_details': np.float64(nan),
 'liability_NTCycl_avg_severity': np.float64(0.0),
 'liability_TrpOx_count': np.int64(0),
 'liability_TrpOx_position': np.int64(-1),
 'liability_TrpOx_length': np.int64(0),
 'liability_TrpOx_severity': np.int64(0),
 'liability_TrpOx_details': np.float64(nan),
 'liability_TrpOx_positions': np.float64(nan),
 'liability_TrpOx_num_positions': np.int64(0),
 'liability_TrpOx_global_details': np.float64(nan),
 'liability_TrpOx_avg_severity': np.float64(0.0),
 'liability_AspBridge_count': np.int64(0),
 'liability_AspBridge_position': np.int64(-1),
 'liability_AspBridge_length': np.int64(0),
 'liability_AspBridge_severity': np.int64(0),
 'liability_AspBridge_details': np.float64(nan),
 'liability_AspBridge_positions': np.float64(nan),
 'liability_AspBridge_num_positions': np.int64(0),
 'liability_AspBridge_global_details': np.float64(nan),
 'liability_AspBridge_avg_severity': np.float64(0.0),
 'liability_AspCleave_position': np.int64(23),
 'liability_AspCleave_length': np.int64(2),
 'liability_AspCleave_severity': np.int64(10),
 'liability_AspCleave_details': np.float64(nan),
 'liability_AspCleave_positions': nan,
 'liability_AspCleave_num_positions': np.int64(0),
 'liability_AspCleave_global_details': np.float64(nan),
 'liability_AspCleave_avg_severity': np.float64(0.0),
 'liability_HydroPatch_position': np.int64(-1),
 'liability_HydroPatch_length': np.int64(0),
 'liability_HydroPatch_severity': np.int64(0),
 'liability_HydroPatch_details': np.float64(nan),
 'liability_HydroPatch_positions': nan,
 'liability_HydroPatch_num_positions': np.int64(0),
 'liability_HydroPatch_global_details': np.float64(nan),
 'liability_HydroPatch_avg_severity': np.float64(0.0),
 'liability_MetOx_count': np.int64(0),
 'liability_MetOx_position': np.int64(-1),
 'liability_MetOx_length': np.int64(0),
 'liability_MetOx_severity': np.int64(0),
 'liability_MetOx_details': np.float64(nan),
 'liability_MetOx_positions': np.float64(nan),
 'liability_MetOx_num_positions': np.int64(0),
 'liability_MetOx_global_details': np.float64(nan),
 'liability_MetOx_avg_severity': np.float64(0.0),
 'liability_DPP4_count': np.int64(0),
 'liability_DPP4_position': np.int64(-1),
 'liability_DPP4_length': np.int64(0),
 'liability_DPP4_severity': np.int64(0),
 'liability_DPP4_details': np.float64(nan),
 'liability_DPP4_positions': np.float64(nan),
 'liability_DPP4_num_positions': np.int64(0),
 'liability_DPP4_global_details': np.float64(nan),
 'liability_DPP4_avg_severity': np.float64(0.0),
 'liability_ProtTryp_position': np.int64(-1),
 'liability_ProtTryp_length': np.int64(0),
 'liability_ProtTryp_severity': np.int64(0),
 'liability_ProtTryp_details': np.float64(nan),
 'liability_ProtTryp_positions': '1-61',
 'liability_ProtTryp_num_positions': np.int64(15),
 'liability_ProtTryp_global_details': np.float64(nan),
 'liability_ProtTryp_avg_severity': np.float64(10.0),
 'liability_UnpairedCys_position': np.float64(nan),
 'liability_UnpairedCys_length': np.float64(nan),
 'liability_UnpairedCys_severity': np.float64(nan),
 'liability_UnpairedCys_details': np.float64(nan),
 'liability_violations_summary': 'AspCleave(pos23,sev10); ProtTrypx15(pos1-61,sev10)',
 'native_rmsd': np.float64(0.0),
 'native_rmsd_bb': np.float64(0.0),
 'bindsite_under_3rmsd': np.float64(0.0),
 'bindsite_under_4rmsd': np.float64(0.0),
 'bindsite_under_5rmsd': np.float64(0.0),
 'bindsite_under_6rmsd': np.float64(0.0),
 'bindsite_under_7rmsd': np.float64(0.0),
 'bindsite_under_8rmsd': np.float64(0.0),
 'bindsite_under_9rmsd': np.float64(0.0),
 'native_rmsd_refolded': np.float64(0.0),
 'native_rmsd_bb_refolded': np.float64(0.0),
 'designfolding-bb_rmsd': np.float64(0.45156),
 'designfolding-bb_rmsd_design': np.float64(0.45156),
 'designfolding-bb_rmsd_target': np.float64(nan),
 'designfolding-bb_rmsd_design_target': np.float64(nan),
 'designfolding-bb_target_aligned_rmsd_design': np.float64(nan),
 'designfolding-bb_rmsd<2.5': np.True_,
 'designfolding-bb_target_aligned<2.5': np.False_,
 'designfolding-bb_designability_rmsd_2': np.True_,
 'designfolding-bb_designability_rmsd_4': np.True_,
 'designfolding-ligand_iptm': np.float64(0.0),
 'designfolding-interaction_pae': np.float64(0.0),
 'designfolding-min_interaction_pae': np.float64(100000.25),
 'designfolding-min_design_to_target_pae': np.float64(100000.25),
 'designfolding-iptm': np.float64(0.0),
 'designfolding-ptm': np.float64(0.69011),
 'designfolding-protein_iptm': np.float64(0.0),
 'designfolding-design_iptm': np.float64(0.0),
 'designfolding-design_iiptm': np.float64(0.0),
 'designfolding-design_to_target_iptm': np.float64(0.0),
 'designfolding-target_ptm': np.float64(0.0),
 'designfolding-design_ptm': np.float64(0.69011),
 'designfolding-min_interaction_pae<1.5': np.False_,
 'designfolding-min_interaction_pae<2': np.False_,
 'designfolding-min_interaction_pae<2.5': np.False_,
 'designfolding-min_interaction_pae<3': np.False_,
 'designfolding-min_interaction_pae<4': np.False_,
 'designfolding-min_interaction_pae<5': np.False_,
 'designfolding-design_ptm>80': np.False_,
 'designfolding-design_ptm>75': np.False_,
 'designfolding-design_iptm>80': np.False_,
 'designfolding-design_iptm>70': np.False_,
 'designfolding-design_iptm>60': np.False_,
 'designfolding-design_iptm>50': np.False_,
 'bb_rmsd': np.float64(0.81904),
 'bb_rmsd_design': np.float64(0.4236),
 'bb_rmsd_target': np.float64(0.7897),
 'bb_rmsd_design_target': np.float64(1.29923),
 'bb_target_aligned_rmsd_design': np.float64(1.29923),
 'bb_rmsd<2.5': np.True_,
 'bb_target_aligned<2.5': np.True_,
 'bb_designability_rmsd_2': np.True_,
 'bb_designability_rmsd_4': np.True_,
 'ligand_iptm': np.float64(0.0),
 'interaction_pae': np.float64(16.17085),
 'min_interaction_pae': np.float64(6.35154),
 'iptm': np.float64(0.93037),
 'ptm': np.float64(0.94471),
 'protein_iptm': np.float64(0.93037),
 'design_iptm': np.float64(0.7302),
 'design_iiptm': np.float64(0.74721),
 'target_ptm': np.float64(0.95568),
 'min_interaction_pae<1.5': np.False_,
 'min_interaction_pae<2': np.False_,
 'min_interaction_pae<2.5': np.False_,
 'min_interaction_pae<3': np.False_,
 'min_interaction_pae<4': np.False_,
 'min_interaction_pae<5': np.False_,
 'design_ptm>80': np.True_,
 'design_ptm>75': np.True_,
 'design_iptm>80': np.False_,
 'design_iptm>70': np.True_,
 'design_iptm>60': np.True_,
 'design_iptm>50': np.True_,
 'design_sasa_unbound_refolded': np.float64(45313.19531),
 'design_sasa_bound_refolded': np.float64(44261.58203),
 'plip_saltbridge_refolded': np.int64(3),
 'liability_details': np.float64(nan),
 'filter_rmsd_design': np.float64(0.4236),
 'neg_min_design_to_target_pae': np.float64(-6.35154),
 'neg_design_hydrophobicity': np.float64(-51.178),
 'neg_design_largest_hydrophobic_patch_refolded': np.float64(-835.42358),
 'neg_min_interaction_pae': np.float64(-6.35154),
 'has_x': np.False_,
 'num_filters_passed': np.int64(9),
 'pass_has_x_filter': np.True_,
 'pass_filters': np.True_,
 'pass_filter_rmsd_filter': np.True_,
 'pass_filter_rmsd_design_filter': np.True_,
 'pass_designfolding-filter_rmsd_filter': np.True_,
 'pass_ALA_fraction_filter': np.True_,
 'pass_GLY_fraction_filter': np.True_,
 'pass_GLU_fraction_filter': np.True_,
 'pass_LEU_fraction_filter': np.True_,
 'pass_VAL_fraction_filter': np.True_,
 'rank_design_to_target_iptm': np.float64(2.0),
 'rank_design_ptm': np.float64(2.0),
 'rank_neg_min_design_to_target_pae': np.float64(2.0),
 'rank_plip_hbonds_refolded': np.float64(0.5),
 'rank_plip_saltbridge_refolded': np.float64(1.0),
 'rank_delta_sasa_refolded': np.float64(0.5),
 'max_rank': np.float64(2.0),
 'secondary_rank': np.int64(1),
 'quality_score': np.float64(1.0),
 'sequence': 'KLKEEALKLLEEAKKLIEEGDIDGALEHLEKALEVARKLDLESRKEILEKIIELLKELRKKIE'}